Traceback (most recent call last):
  File "C:\Users\lgeil.IL-MF10-NB100TS\DE_PERSONAL\chat_messaging_kafka\consumer.py", line 62, in <module>
    consumer1()
  File "C:\Users\lgeil.IL-MF10-NB100TS\DE_PERSONAL\chat_messaging_kafka\consumer.py", line 29, in consumer1
    consumer.commit()
  File "C:\Users\lgeil.IL-MF10-NB100TS\Miniconda3\envs\myenv\lib\site-packages\kafka\consumer\group.py", line 527, in commit
    self._coordinator.commit_offsets_sync(offsets)
  File "C:\Users\lgeil.IL-MF10-NB100TS\Miniconda3\envs\myenv\lib\site-packages\kafka\coordinator\consumer.py", line 521, in commit_offsets_sync
    raise future.exception # pylint: disable-msg=raising-bad-type
kafka.errors.CommitFailedError: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.
            

Process finished with exit code 1
